# HW 4 - Python
## By Nathan Smith


In [21]:
import pandas as pd
import numpy as np

csvfile = 'https://www.dropbox.com/s/jgtk2x9l1kh8oz4/Travel%20Pony%20Facebook.csv?dl=1'

FBPony = pd.read_csv(csvfile)


In [22]:
#Calculates the cost per impressions and then adds that data as a column
Cost_Per_Impression = (FBPony.loc[:,'Amount Spent (USD)'])/(FBPony.loc[:,'Impressions'])
FBPony['Cost Per Impression'] = Cost_Per_Impression


In [5]:
import arrow

#initializes a place to store the day of the week 
dayofweek = []

#loop that iterates through FBPony data and gets the start date value
for row in range(len(FBPony)):
    date = arrow.get(FBPony['Start Date'][row], 'M/D/YY')
    dayofweek.append(date.isoweekday())
    
#takes the iterated date data from the above for loop and stores it
FBPony['Day'] = dayofweek

#groups the days by each day
group = FBPony.groupby('Day')

#calculates the mean for each day group
group.aggregate(np.mean)
#Friday is the most expensive day. Thursday and Sunday are also very expensive
#Saturday is the cheapest day.


Reach  Frequency  Impressions     Clicks  Unique Clicks  \
Day                                                                  
1    1842.864177   1.017603  2525.074703   7.536503       6.521222   
2    1889.215190   1.012193  1926.738397   9.419831       8.151899   
3    1494.235195   1.009059  1516.478849   7.781726       6.524535   
4    1413.081882   1.011668  1449.837979   8.054007       6.980836   
5    2238.474104   1.012024  3037.984064  10.147410       8.848606   
6    2281.755511   1.014517  3152.184369  10.014028       8.857715   
7    2203.596639   1.016073  2775.644958   9.981092       8.808824   

     Amount Spent (USD)  Page Likes  Page Engagement  Post Engagement  \
Day                                                                     
1              7.427097    0.670628         7.634975         6.964346   
2              9.455084    1.094937         9.679325         8.584388   
3              7.956024    0.934010         8.131980         7.197970   
4              7.640209    0.855401         8.634146         7.778746   
5             10.014741    0.844622        10.635458         9.790837   
6              9.625511    0.923848         9.573146         8.649299   
7              9.676534    0.831933         8.794118         7.960084   

     Post Likes  Post Comments  Post Shares  Photo Views  Website Clicks  \
Day                                                                        
1      1.095076       0.040747     0.225806     2.994907        2.607810   
2      1.280591       0.065401     0.202532     3.877637        3.158228   
3      1.241963       0.067682     0.187817     3.225042        2.475465   
4      1.371080       0.094077     0.200348     4.012195        2.101045   
5      1.424303       0.051793     0.250996     4.745020        3.318725   
6      1.102204       0.048096     0.212425     3.595190        3.691383   
7      0.962185       0.029412     0.218487     3.220588        3.529412   

     Cost per Page Engagement (USD)  Cost Per Impression  
Day                                                       
1                          0.492924             0.002910  
2                          0.592907             0.003040  
3                          0.539237             0.002981  
4                          0.560598             0.003398  
5                          0.476606             0.004097  
6                          0.415395             0.002629  
7                          0.491080             0.003688

In [9]:
#calculate the correlation of amount spent compared to reach, freq, unique clicks, and page likes
ASandR = np.corrcoef(FBPony['Amount Spent (USD)'],FBPony['Reach'])
ASandFreq = np.corrcoef(FBPony['Amount Spent (USD)'],FBPony['Frequency'])
ASandUC = np.corrcoef(FBPony['Amount Spent (USD)'],FBPony['Unique Clicks'])
ASandPl = np.corrcoef(FBPony['Amount Spent (USD)'],FBPony['Page Likes'])
print('ASandR')
print(ASandR)
###
print('ASandFreq')
print(ASandFreq)
###
print('ASandUC')
print(ASandUC)
###
print('ASandPl')
print(ASandPl)

ASandR
[[1.         0.70312381]
 [0.70312381 1.        ]]
ASandFreq
[[1.         0.13020087]
 [0.13020087 1.        ]]
ASandUC
[[1.         0.88299318]
 [0.88299318 1.        ]]
ASandPl
[[1.         0.75761193]
 [0.75761193 1.        ]]


In [10]:
import statsmodels.api as sm

In [16]:
y=FBPony['Unique Clicks']
x=FBPony[['Reach','Frequency']]

model = sm.OLS(y,x).fit()
predictions = model.predict(x)

print(model.summary())




#################
print('Frequency most strongly predicts unique clicks. The coefficient for frequency is much larger than reach.')

                            OLS Regression Results                            
Dep. Variable:          Unique Clicks   R-squared:                       0.557
Model:                            OLS   Adj. R-squared:                  0.556
Method:                 Least Squares   F-statistic:                     2325.
Date:                Thu, 18 Oct 2018   Prob (F-statistic):               0.00
Time:                        16:35:25   Log-Likelihood:                -15973.
No. Observations:                3705   AIC:                         3.195e+04
Df Residuals:                    3703   BIC:                         3.196e+04
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Reach          0.0019   3.12e-05     62.490      0.0